# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1389ab9b1e75e4de2ea1844c9ed50ba90e6567a166504f4f71d36b90f3270404e5e684f268d77482634d71ef81e346501673bd48de9d140c546e67519e85f935

test:
  secret_key_base: 14d7cd2ebfb01cfb4c661f48fc3b6c48f067f505764bc427e98ec097203642efd8bd110e6297a803a2061a09837963898da38f172f8352e5c8c022113bb75d3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
